// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mrcpuvkwyqnalagomyes.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1yY3B1dmt3eXFuYWxhZ29teWVzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzMTAzNjYsImV4cCI6MjA3MTg4NjM2Nn0.RDXr3jnFSxqPjoRSsivhmClwc10gqYVaZPuZg2k9rjo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});